[deps]
ArbNumerics = "7e558dbc-694d-5a72-987c-6f4ebed21442"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Format = "1fa38f19-a742-5d3f-a2b9-30dd87b9d5f8"
Integrals = "de52edbc-65ea-441a-8357-d3a637375a31"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
MCIntegration = "ea1e2de9-7db7-4b42-91ee-0cd1bf6df167"
NaturalUnits = "61adfb09-12d1-4e3c-91b1-54bf68ca093d"
